const clients = [
	{
		_id: '664e7702629d03eab7cd801e',
		benefitsDesired:
			'Dr. Hazzah has recommended double strength silver bullet product',
		breed: 'Labrador Retriever',
		firstName: 'Kristen',
		howReferred: 'Dr Hazzah',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Silvia',
		mailingAddress:
			'32 YOUNGS LN\r\nFREEPORT, ME, 04032-6261\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '7',
		petClinicName: 'Green Nile',
		petConditions: 'Cancer',
		petCurrentMedications: 'CCNU, procarbazine, prednisone, visbiome probiotic',
		petFoodAllergy: 'none',
		petGender: 'Female - Spayed',
		petName: 'Grace Silvia',
		petWeight: '65',
		phoneNumber: '(207) 799-8580',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-22T18:51:43.000Z',
		},
	},
	{
		_id: '664e4acb7bbe4dad273efbb6',
		benefitsDesired: 'no more seizures',
		breed: 'Goldendoodle',
		firstName: 'Lori',
		howReferred: 'Dr Hazzah',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Bernstein',
		mailingAddress:
			'139 EDGEMONT MEADOWS RD\r\nDURANGO, CO, 81301-8444\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '3',
		petClinicName: 'Green Nile',
		petConditions: 'Seizures',
		petCurrentMedications: 'Keppra\r\nZonisamide',
		petFoodAllergy: 'none',
		petGender: 'Male - Neutered',
		petName: 'Mookie',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5922161840404702617/IMG_2133.jpeg',
		petWeight: '42',
		phoneNumber: '(818) 836-0091',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-22T15:43:04.000Z',
		},
	},
	{
		_id: '664e3875708cbd9e2b936fa1',
		benefitsDesired: 'Improve his health',
		breed: 'Beagle',
		firstName: 'Diana',
		howReferred: 'Green nill recommendation',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Quintana',
		mailingAddress:
			'8104 VISTA ESTRELLA LN SW\r\nALBUQUERQUE, NM, 87121-8947\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '13.5',
		petClinicName: 'Eprogresstracker',
		petConditions: 'Cancer',
		petCurrentMedications: 'Denamarin',
		petFoodAllergy: 'None',
		petGender: 'Male - Neutered',
		petName: 'Paco Quintana',
		petWeight: '45',
		phoneNumber: '(505) 459-8753',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-22T14:24:51.000Z',
		},
	},
	{
		_id: '664bd08533c153e7766d26dd',
		benefitsDesired: 'reduce anxiety',
		breed: 'multipoo',
		firstName: 'Lynne',
		howReferred: 'friend',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Zapata',
		mailingAddress:
			'13477 TIVERTON RD\r\nSAN DIEGO, CA, 92130-1019\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '9',
		petClinicName: 'Torrey Pines Animal Hospital',
		petConditions: 'Anxiety',
		petCurrentMedications: 'nothing daily',
		petFoodAllergy: 'none',
		petGender: 'Male - Neutered',
		petName: 'Porter',
		petWeight: '12',
		phoneNumber: '(949) 280-4110',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-20T18:36:51.000Z',
		},
	},
	{
		_id: '664e3453099d712715fa3171',
		benefitsDesired: 'reduce anxiety',
		breed: 'multipoo',
		firstName: 'Lynne',
		howReferred: 'friend',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Zapata',
		mailingAddress:
			'13477 TIVERTON RD\r\nSAN DIEGO, CA, 92130-1019\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '9',
		petClinicName: 'Torrey Pines Animal Hospital',
		petConditions: 'Anxiety',
		petCurrentMedications: 'nothing daily',
		petFoodAllergy: 'none',
		petGender: 'Male - Neutered',
		petName: 'Porter',
		petWeight: '12',
		phoneNumber: '(949) 280-4110',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-20T18:36:51.000Z',
		},
	},
];

export default clients;
