const clients = [
	{
		_id: '664e4acb7bbe4dad273efbb6',
		benefitsDesired: 'no more seizures',
		breed: 'Goldendoodle',
		email: 'loloberns3@gmail.com',
		firstName: 'Lori',
		howReferred: 'Dr Hazzah',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Bernstein',
		mailingAddress:
			'139 EDGEMONT MEADOWS RD\r\nDURANGO, CO, 81301-8444\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '3',
		petClinicName: 'Green Nile',
		petConditions: 'Seizures',
		petCurrentMedications: 'Keppra\r\nZonisamide',
		petFoodAllergy: 'none',
		petGender: 'Male - Neutered',
		petName: 'Mookie',
		petImage: '/images/664e4acb7bbe4dad273efbb6.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5922161840404702617/IMG_2133.jpeg',
		petVet: 'Dr Trina Hazzah',
		petWeight: '42',
		phoneNumber: '(818) 836-0091',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-22T15:43:04.000Z',
		},
	},
	{
		_id: '6646777d5e4298a0dbeead8a',
		benefitsDesired: 'Comfort, pain relief, sleep',
		breed: 'English bulldog',
		email: 'linda.vellanti@yahoo.com',
		firstName: 'Linda',
		howReferred: 'Family member',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Vellanti',
		mailingAddress:
			'4242 BOULDER VIEW DR\r\nBELMONT, MI, 49306-9145\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '4',
		petClinicName: 'Great Lakes animal hospital and blue pearl oncology',
		petConditions: 'Cancer',
		petCurrentMedications: 'Gabapentin and rymidal',
		petFoodAllergy: 'Turkey',
		petGender: 'Female - Spayed',
		petName: 'Maci',
		petImage: '/images/6646777d5e4298a0dbeead8a.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5917033392392681404/IMG_8004.jpeg',
		petWeight: '57',
		phoneNumber: '(616) 890-7695',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-16T17:15:39.000Z',
		},
	},
	{
		_id: '66456d0010f3f2dea0b32152',
		benefitsDesired:
			'Appetite to help gain weight, Comfort, Reduce the weakness in hind legs & overall wellness during cancer treatment. We want to keep our baby boy for as long as possible with good quality of life.  His IG is @the_doggie_days',
		breed: 'Maltese',
		email: 'gauri.tapan@gmail.com',
		firstName: 'GAURI',
		howReferred:
			'Through a friend whose dog is going through cancer treatment ',
		intakeActionRequested: 'Email me as I have questions',
		lastName: 'SIKKA',
		mailingAddress:
			'151 E 31ST ST APT 10H\r\nNEW YORK, NY, 10016-9503\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Zelle',
		petAge: '15',
		petClinicName: 'Rivergate Veterinary Clinic ',
		petConditions:
			'Cancer; Early CKD (canine kidney disease) and weakness in hind legs',
		petCurrentMedications:
			'Zofran, Cerenia, Omeprazole, Levothyroxin, Metronizadole (as needed), Metaclopromide (as needed) & Benadryl (as needed), Potassium supplement. \r\n',
		petFoodAllergy: 'Dairy sometimes upsets his stomach. ',
		petGender: 'Male - Neutered',
		petName: 'Dior',
		petImage: '/images/66456d0010f3f2dea0b32152.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5916351172566117024/Facetune_22-04-2024-14-56-57.jpeg',
		petVet: 'Dr Peter Kross',
		petWeight: '8.5',
		phoneNumber: '(646) 330-1551',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-15T22:18:37.000Z',
		},
	},
	{
		_id: '6643e493cee7bcb796592f2d',
		benefitsDesired: 'Shrink MCT & relief of painful from IVDD',
		breed: 'Pitbull',
		email: 'lovebully50@gmail.com',
		firstName: 'Valerie',
		howReferred: 'DR HAZZAH',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Hernandez',
		mailingAddress:
			'4921 JILLSON ST\r\nCOMMERCE, CA, 90040-1103\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Zelle',
		petAge: '11',
		petClinicName: 'HOLISTIKA VETERINARIAN ',
		petConditions: 'Cancer; Anxiety; Pain; IVDD Allergies',
		petCurrentMedications:
			'Prednisone, benadryl, pepcid,thyroid tabs.\r\nChines herbs, CBD, Mushrooms',
		petFoodAllergy: 'Chicken egg ',
		petGender: 'Male - Neutered',
		petName: 'BULLY',
		petImage: '/images/6643e493cee7bcb796592f2d.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5915346568291354073/Screenshot_20240506_193558_Chrome.jpg',
		petVet: 'DR MAGDA DR HAZZAH',
		petWeight: '75',
		phoneNumber: '(323) 385-9642',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-14T18:24:16.000Z',
		},
	},
	{
		_id: '663cd618f38f04fb42cdffbb',
		benefitsDesired:
			'My primary objectives are nausea/vomiting control and pain relief from the pancreatitis and suspected IBD. Sam is already a very relaxed cat, so I don not want to see him sedated or give him anything that will impair his ability to be as active as possible.',
		breed: 'Domestic shorthair',
		email: 'emmika.elkin@hotmail.com',
		firstName: 'Emmika',
		howReferred: 'Referral from a friend',
		intakeActionRequested: 'Email me as I have questions',
		lastName: 'Elkin',
		mailingAddress:
			'1912 SUNSHINE VALLEY RD\r\nMOSS BEACH, CA, 94038-9780\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Zelle',
		petAge: '8',
		petClinicName: 'Coastal Cat Clinic',
		petConditions: 'Pancreatitis, Diabetes, Suspected IBD',
		petCurrentMedications:
			'Cerenia transdermal - once/day\r\nBuprenorphine oral - twice/day\r\nZofran oral - twice/day\r\nZobaline oral - twice/day\r\nLantus insulin - twice/day',
		petFoodAllergy:
			'Unknown, but currently on a raw novel protein diet (rabbit, primarily) due to his diagnoses (both confirmed and suspected)',
		petGender: 'Male - Neutered',
		petName: 'Sam',
		petImage: '/images/663cd618f38f04fb42cdffbb.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5910721970911268126/IMG_1982.jpeg',
		petVet: '',
		petWeight: '12',
		phoneNumber: '(925) 528-9599',
		species: 'Cat',
		submissionDate: {
			$date: '2024-05-09T09:56:37.000Z',
		},
	},
	{
		_id: '663b66a1a2d5ccceedda0cd9',
		benefitsDesired:
			'So he is not in so much pain and to make decisions for his health/wellbeing',
		breed: 'Quarter Horse',
		email: 'themeetinghousefarm@gmail.com',
		firstName: 'Lynn',
		howReferred: 'Family',
		intakeActionRequested: 'Email me as I have questions',
		lastName: 'Thompson',
		mailingAddress:
			'371 OLD TULPEHOCKEN RD\r\nBIRDSBORO, PA, 19508-8654\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Zelle',
		petAge: '6',
		petClinicName: 'Willow Creek Equine ',
		petConditions: 'Arthritis; Tension/ Ring Bone',
		petCurrentMedications: 'Herbs for pain',
		petFoodAllergy: 'N/A',
		petGender: 'Male - Neutered',
		petName: 'Tulpe Blue',
		petImage: '/images/663b66a1a2d5ccceedda0cd9.png',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5909781256811906790/IMG_0173.png',
		petVet: 'Dr Kendra Faeke',
		petWeight: '97',
		phoneNumber: '(415) 991-9859',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-08T07:48:45.000Z',
		},
	},
	{
		_id: '663a72d999653b738646afc7',
		benefitsDesired: 'Back to moving and walking with me ',
		breed: 'Golden retriever ',
		email: 'pamelanorton@mac.com',
		firstName: 'Pamela',
		howReferred: 'Web',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Norton',
		mailingAddress:
			'9583 W OLYMPIC BLVD\r\nBEVERLY HILLS, CA, 90212-4243\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '14',
		petClinicName: 'Small animal hospital',
		petConditions: 'Arthritis',
		petCurrentMedications: 'None just green mussels for joints ',
		petFoodAllergy: 'None',
		petGender: 'Female - Spayed',
		petName: 'Mochi',
		petImage: '/images/663a72d999653b738646afc7.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5909157051432068254/IMG_7249.jpeg',
		petVet: '',
		petWeight: '80',
		phoneNumber: '(303) 898-0804',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-07T14:28:25.000Z',
		},
	},
	{
		_id: '663a37d523ade7956567fad9',
		benefitsDesired: 'Eliminate gagging/projectile spitting up, vomiting.',
		breed: 'Chiweenie',
		email: 'amandagalesf@gmail.com',
		firstName: 'Amanda',
		howReferred: 'Gary Richter',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Gale-Bando',
		mailingAddress:
			'644 DANUBE WAY\r\nCOSTA MESA, CA, 92626-3144\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo; Zelle',
		petAge: '1',
		petClinicName: 'Newport Mesa Animal Hospital',
		petConditions: 'GI Distress: projectile spitting up, sometime vomiting',
		petCurrentMedications:
			'N/A - although on temporarily on Metranidazole for week-long vomiting episodes',
		petFoodAllergy:
			'Not sure but Betty has a sensitive stomach. Once we put her on a pork-based formula, she eats fine but before that, was a picky eater.',
		petGender: 'Female - Spayed',
		petName: 'Betty',
		petImage: '/images/663a37d523ade7956567fad9.png',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5909006103858689538/IMG-0412.PNG',
		petVet: 'Dr Tom',
		petWeight: '11',
		phoneNumber: '(714) 788-9625',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-07T10:16:50.000Z',
		},
	},
	{
		_id: '6637c922389b6aff4c4cb185',
		benefitsDesired:
			'Ive noticed she seems more stiff in her hips & neck. I would like to give her relief to have better mobility. ',
		breed: 'Maltipoo',
		email: 'kristaaspence@gmail.com',
		firstName: 'Krista',
		howReferred: 'Friend',
		intakeActionRequested: 'Call me as I have questions',
		lastName: 'Spence',
		mailingAddress:
			'919 NEPTUNE AVE\r\nENCINITAS, CA, 92024-2065\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Zelle',
		petAge: '14',
		petClinicName: 'Kandu',
		petConditions: 'Arthritis; Pain; Cardiac Disease',
		petCurrentMedications: 'Gabapentin, vetmedin',
		petFoodAllergy: 'No food allergies ',
		petGender: 'Female - Spayed',
		petName: 'Kandu',
		petImage: '/images/6637c922389b6aff4c4cb185.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5907411992163937717/image.jpg',
		petVet: '',
		petWeight: '17',
		phoneNumber: '(760) 216-3033',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-05T13:59:59.000Z',
		},
	},
	{
		_id: '66351c6da47e850ba18a15e2',
		benefitsDesired: 'Relief from pain.  To make him comfortable.',
		breed: 'Golden Retriever',
		email: 'abchimley@epbfi.com',
		firstName: 'Alison',
		howReferred: 'our vet',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Chimley',
		mailingAddress:
			'1 ROCK CREST LN\r\nSIGNAL MTN, TN, 37377-2303\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '12',
		petClinicName: 'CHAI Vet',
		petConditions: 'Anxiety; Arthritis; Pain',
		petCurrentMedications:
			'Gabapentin, Cosequin, Fish Oil, Meticam (not taking at this time), Trylostane (not taking at this time)',
		petFoodAllergy: 'No known allergies',
		petGender: 'Male - Neutered',
		petName: 'Harper',
		petImage: '/images/66351c6da47e850ba18a15e2.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5905659052314241132/IMG_7037.jpeg',
		petVet: '',
		petWeight: '71',
		phoneNumber: '(865) 257-0911',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-03T13:18:25.000Z',
		},
	},
	{
		_id: '664f8dd9675a4f551eee6981',
		benefitsDesired:
			'Pain control/reduction from what will be progressing cancer.\r\nHopefully some clinical improvement of inflammation maybe be  some anti-cancer effects to slow down the cancer cell proliferation.\r\nOverall improvement in everyday quality of life. Oreo the cat currently eats actively on her own (1.5 cans of wet food plus dry kibble when she wants) every day. She drinks water well every day. ',
		breed: 'Domestic Short Hair Feline',
		email: 'lia.aquino@yahoo.com',
		firstName: 'Lia',
		howReferred: 'Green Nile Dr Trina Hazzah DVM Oncology',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Aquino',
		mailingAddress:
			'4407 FRANCIS AVE UNIT 208\r\nLOS ANGELES, CA, 90005-3702\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo',
		petAge: '18',
		petClinicName: 'True Care For Pets',
		petConditions: 'Cancer',
		petCurrentMedications:
			'Gabapentin oral 250 mg/5 mL, 0.05 - 0.1 mL every 8 hours.\r\nFish oil 0.5 mL a day\r\nCosiquin tablet joint support 1 tab a day',
		petFoodAllergy: 'None',
		petGender: 'Female - Spayed',
		petName: 'Oreo Aquino',
		petImage: '/images/664f8dd9675a4f551eee6981.png',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5922988868307136854/Oreo%2018th%20bday%20Apr%2030%202024.PNG',
		petVet: 'Karen Koo DVM',
		petWeight: '6',
		phoneNumber: '(323) 823-2954',
		species: 'Cat',
		submissionDate: {
			$date: '2024-05-23T14:41:26.000Z',
		},
	},

	{
		_id: '6632c5578ef11d5f50fc539e',
		benefitsDesired: 'Decrease on fixating on object and reducing anxiety.',
		breed: 'English bulldog',
		email: 'christineyna@gmail.com',
		firstName: 'Christine',
		howReferred: 'Shadows fund',
		intakeActionRequested: 'Send an invoice and payment instructions',
		lastName: 'Na',
		mailingAddress:
			'4170 ELM AVE UNIT 319\r\nLONG BEACH, CA, 90807-6913\r\nUnited States\r\nAddress is valid and deliverable.',
		paymentMethodChoice: 'Venmo; Zelle',
		petAge: '6',
		petClinicName: 'Shadows fund',
		petConditions: 'Anxiety; Seizures; Pain',
		petCurrentMedications: 'Daily multivitamin for fur and joint health',
		petFoodAllergy: 'None',
		petGender: 'Male - Neutered',
		petName: 'Dexter',
		petImage: '/images/6632c5578ef11d5f50fc539e.jpg',
		petPhoto:
			'https://www.jotform.com/uploads/ivmholdings/220194948845164/5904125488956058045/IMG_8811.jpeg',
		petVet: 'Cody Rackley',
		petWeight: '36',
		phoneNumber: '(626) 641-4196',
		species: 'Dog',
		submissionDate: {
			$date: '2024-05-01T18:42:28.000Z',
		},
	},
];

export default clients;
